server:
  port: 8080

weather:
  api:
    weather_stack:
      key: 'YOUR_API_KEY'
      weather_url: 'http://api.weatherstack.com/current'
    open_weather_map:
      key: 'YOUR_API_KEY'
      city_url: 'http://api.openweathermap.org/geo/1.0/direct'
      weather_url: 'https://api.openweathermap.org/data/2.5/weather'